<?php
define(_search_txt,"Search");	
define(_Product_Ref_txt,"File Ref.");
define(_vers_check_txt,"English Version");
define(_welcome_txt,"Welcome");
define(_start_ordering_button,"Start Ordering Now");
$_You_have_product_in_cart="You have product in cart";
$_items_txt="items.";
define(_main_menu_txt,"Main Menu");	
define(_howto_txt,"How To");
define(_preference_txt,"Preference");
define(_product_txt,"Files");
define(_view_cart_txt,"View Cart");
define(_track_order_txt,"Track Order");
define(_file_upload_txt,"File Upload");
define(_contact_us_txt,"Contact us");
define(_logout_txt,"Logout");
define(_Your_Cart_txt,"Your Cart");
define(_Edit_txt,"Edit");
define(_Order_Tracking_txt,"Order Tracking");
define(_View_Order_txt,"View Order");
define(_You_can_fill,"You can fill-in order no.");
define(_Track_btn,"Track!");
$_delete_btn="Delete";
$_update_btn="Update";
$_order_now_btn="Order Now";
$_Product_Description_txt="Product Description";
$_Item_added_on_txt="Item added on";
$_view_cart_tip1_txt="To delete items, tick the appropriate box and click 'DELETE' button.";
$_view_cart_tip2_txt="To update items, like editing the quantity, tick the appropriate box and edit before clicking the 'UPDATE' button";
$_view_cart_tip3_txt="To proceed with the order, click 'ORDER NOW' button.";
$_view_cart_tick_txt="*Tick the first appropriate box for select all items";
$_Add_more_product_txt="Add more product";
$_order_status1_txt="Check your order";
$_order_status2_txt="Inquiry Details";
$_order_status3_txt="Payment";
$_order_status4_txt="Confirm";
$_You_have_successfully_txt="You have successfully submitted your order";
$_Cmess1_txt="Please take note of your order number for tracking and other checking purposes. Your order number will also appear on shipping documents.";
$_Order_No_txt="Order No";
$_Click_Here_to_txt="Click Here to";
$_Home_Page_txt="Home Page";
$_ENTER_NEW_ORDER_btn="ENTER NEW ORDER";
$_Your_cart_is_empty="Your cart is empty";
$_All_Categories_lst="All File Categories";
$_All_Products_txt="All Files";
$_Categories_txt="File Categories";
$_Keyword_txt="Keyword";

?>